### ISSUE TITLE
Unable to setup https

### ISSUE THREAD

**Issue by davidclaeysquinones** [Threadfin/Threadfin#175]
I'm unable to setup https for threadfin. The reason I need this is because my client does not accept m3u playlists through http.

My setup is on ubuntu through docker compose:

```
version: '3.5'
services:
    vpn:
       image: qmcgaw/gluetun
       cap_add:
         - NET_ADMIN
       devices:
         - /dev/net/tun:/dev/net/tun
       sysctls:
         - net.ipv6.conf.all.disable_ipv6=0
       environment:
        [sensitive information]
       ports:
         #threadfin
         - 34400:34400
         - 34401:34401 #ssl
       volumes:
           - /data/vpn/vpn:/config
       restart: unless-stopped
    threadfin:
       image: fyb3roptik/threadfin
       environment:
         - PUID=1000
         - PGID=1000
         - TZ=Europe/Madrid
       depends_on:
           - vpn
       network_mode: "service:vpn"
       volumes: 
         - /data/threadfin:/home/threadfin/conf
       restart: unless-stopped
```
I need the traffic for threadfin to go through the vpn container. This setup already works for other containers, and actually I have no issue for http.

I have tried to map port 34401 to 443 in the container, i have changed the settings file manually to 34401, edited in through the web interface. No matter what I do it does not work.

I have also tried to set up https through a proxy (Nginx), redirecting the http port to ssl. 
I also setup the UDPxy setting through a stream host (tcp and udp), and filled in the http and https domain.
