### ISSUE TITLE
[Docker Compose] Permission denied when mounting bin folder

### ISSUE THREAD

**Issue by HamzaM** [Threadfin/Threadfin#52]
**Describe the bug**
Using docker compose and mounting the bin folder gets me "permission denied" in the logs which makes the app not start.

**Server (please complete the following information):**
- OS Linux / Docker
- Threadfin 1.0.7

**To Reproduce**
`docker compose up -d`

using this : 
```
  threadfin:
    container_name: threadfin
    image: fyb3roptik/threadfin
    volumes:
      - $CONFIG_PATH/threadfin/home:/home/threadfin
      - $CONFIG_PATH/threadfin/bin:/home/threadfin/bin
      - $CONFIG_PATH/threadfin/conf:/home/threadfin/conf
      - $CONFIG_PATH/threadfin/conf/data:/home/threadfin/conf/data
      - $CONFIG_PATH/threadfin/conf/backup:/home/threadfin/conf/backup
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - 34400:34400
    restart: unless-stopped
```

**Additional context**
Removing the first 2 lines of the volume, which means not mounting home and bin folders, makes the app work perfectly

**Comment by f00d4tehg0dz** [comment]
same here...

**Comment by Fyb3roptik** [comment]
Are you running this as sudo by any chance?

**Comment by Fyb3roptik** [comment]
Hop on the discord as there are people there that use docker. I do not use it so I cant really help here

**Comment by srhinos** [comment]
Chiming in, I ended up resolving this issue by only defining the conf directory with my `docker-compose.yml` looking like this:
```
version: '3.9'
services:
    threadfin:
        image: fyb3roptik/threadfin
        container_name: threadfin
        hostname: threadfin
        restart: unless-stopped
        networks:
        - default
        ports:
            - "34400:34400"
            - "1901:1900" #1900 used by Plex
        environment:
            - TZ=America/NewYork
            - THREADFIN_BRANCH=beta
            - THREADFIN_DEBUG=3
        volumes:
            - C:\Users\Rhino\Documents\xteve\conf:/home/threadfin/conf:rw
```
